{% set name = "orjson" %}
{% set version = "2.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 910796567d46223a7f4eaea0cc2cb4d3d3adb7a6bccc5ffa8fa2f95b4296d8d9
    # Lucky for us, this doesn't require glib >2.12
  - url: https://static.rust-lang.org/dist/2020-04-26/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux]
    sha256: a723247878b5b65ec511c86108b9adb99bd1fa9b78ed87986283b93bf9e50d20  # [linux]
    folder: rust-nightly
  - url: https://static.rust-lang.org/dist/2020-04-26/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx]
    sha256: 32bc8dc17ded63ca8012d3f425af4e9eb24e1a36831465f0bea4658ab3353422  # [osx]
    folder: rust-nightly
  - url: https://static.rust-lang.org/dist/2020-04-26/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win64]
    sha256: c6fd886231faa52552757da7a1d813b66aa02413218343089008751fd1b56df7  # [win64]
    folder: rust-nightly

build:
  number: 0
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - posix  # [win]
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
      - LICENSE-APACHE
      - LICENSE-MIT
  summary: 'orjson is a fast, correct JSON library for Python.'
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
