{% set name = "orjson" %}
{% set version = "2.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 910796567d46223a7f4eaea0cc2cb4d3d3adb7a6bccc5ffa8fa2f95b4296d8d9
    # Lucky for us, this doesn't require glib >2.12
  - url: https://static.rust-lang.org/dist/2020-04-26/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    sha256: a723247878b5b65ec511c86108b9adb99bd1fa9b78ed87986283b93bf9e50d20
    folder: rust-nightly

build:
  number: 0
  skip: True  # [py<35]
  script:
    - rust-nightly/install.sh --verbose --prefix=$SRC_DIR/rust-nightly-install --disable-ldconfig
    - export PATH=$SRC_DIR/rust-nightly-install/bin:$PATH
    - maturin build --no-sdist --release --strip --manylinux off -C target-feature=+sse2
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - gcc  # [linux]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
      - LICENSE-APACHE
      - LICENSE-MIT
  summary: 'orjson is a fast, correct JSON library for Python.'
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - EntPyle
