{% set name = "python-for-android" %}
  {% set version = "2019.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 701bf784958a958d70222a6d530f5cf2b44603e183638b35fa2a3de6476afba4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - python-for-android

about:
  home: https://github.com/kivy/python-for-android
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Turn your Python application into an Android APK '

  description: |
    python-for-android is a packaging tool for Python apps on Android. You can create your own Python distribution including the modules and dependencies you want, and bundle it in an APK along with your own code.
    Features include;
    Support for building with both Python 2 and Python 3.
    Different app backends including Kivy, PySDL2, and a WebView with Python webserver.
    Automatic support for most pure Python modules, and built in support for many others, including popular dependencies such as numpy and sqlalchemy.
    Multiple architecture targets, for APKs optimised on any given device.
  doc_url: http://python-for-android.readthedocs.io
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - EntPyle
